name: adv-diff
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx
  - python-gmsh
  - numpy
  - matplotlib
  - ipykernel
  - jupytext
  - nodejs
  - pip>=20.1
  - meshio
  - pip:
      - "mystmd"
      - pyvista
