name: adv-diff
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx
  - python-gmsh
  - numpy
  - matplotlib
  - ipykernel
  - jupytext
  - nbconvert
  - nodejs
  - pip>=20.1
  - meshio
  - adios4dolfinx
  - pip:
      - "mystmd"
      - pyvista
      - io4dolfinx
