name: Test Notebooks

on: [push]

jobs:
  test-notebooks:
    name: Execute example notebooks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up environment
      uses: mamba-org/setup-micromamba@v3
      with:
        environment-file: environment.yml
        cache-environment: true
        init-shell: bash

    - name: Execute notebooks
      shell: bash -el {0}
      run: |
        jupyter nbconvert --to notebook --execute \
          --ExecutePreprocessor.timeout=600 \
          --ExecutePreprocessor.kernel_name=python3 \
          notebooks/example_1/mwe_1.ipynb
        jupyter nbconvert --to notebook --execute \
          --ExecutePreprocessor.timeout=600 \
          --ExecutePreprocessor.kernel_name=python3 \
          notebooks/example_2/mwe_2.ipynb
        jupyter nbconvert --to notebook --execute \
          --ExecutePreprocessor.timeout=600 \
          --ExecutePreprocessor.kernel_name=python3 \
          notebooks/example_3/mwe_3.ipynb
        jupyter nbconvert --to notebook --execute \
          --ExecutePreprocessor.timeout=600 \
          --ExecutePreprocessor.kernel_name=python3 \
          notebooks/example_4/mwe_4.ipynb
